app:
  appName: ueba
  port: :8080
  debug: true

datasource:
  databaseUrl: ueba:ueba1234!@tcp(121.37.208.176:3306)/ueba?charset=utf8&parseTime=True&loc=Local
  charset: utf8
  # 设置连接池中的最大闲置连接数
  # 如果大于最大开启连接数，则新的最大闲置连接数会减小到匹配最大开启连接数的限制
  # 如果 <= 0，不会保留闲置连接
  maxIdleConns: 10
  # 如果 <= 0，不会限制最大开启连接数，默认为0（无限制）
  maxOpenConns: 50
  # 一个连接的最大时长，单位秒
  connMaxLifetime: 60
  # 慢查询阈值,单位秒
  slowThreshold: 3
  prefix: e_
  showSql: true

redis:
  #配置redis地址
  database: 0
  host: 106.55.159.234
  port: 6379
  password: 19881227=shb

log:
  level: debug   #debug,info,error